#!/bin/bash
#
# Configured as part of the 1-Click Image build process
function echoY
{
    FLAG=$1
    shift
    echo -e "\033[38;5;148m$FLAG\033[39m$@"
}
function echoB()
{
    FLAG=$1
    shift
    echo -e "\033[1;4;94m$FLAG\033[0m$@"
}
function echoG
{
    FLAG=$1
    shift
    echo -e "\033[32m$FLAG\033[0m$@"
}

function echoBOLD
{
    FLAG=$1
    shift
    echo -e "\033[1m$FLAG\033[0m$@"
}

function echoCYAN
{
    FLAG=$1
    shift
    echo -e "\033[1;36m$FLAG\033[0m$@"
}

verlte() {
    [ "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
}
verlt() {
    [ "$1" = "$2" ] && return 1 || verlte $1 $2
}

RAM=$(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')
LOAD=$(uptime | awk -F'[a-z]:' '{ print $2}')
DISK=$(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')
CPU=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')

LOCAL_VERSION=$(cat /usr/local/CyberCP/version.txt | sed -z 's/\n/./g')
LAST_VERSION=$(curl -s https://cyberpanel.net/version.txt | grep -Eo '[0-9]'|sed -z 's/\n/./g')
MYIP=$(cat /etc/cyberpanel/machineIP)

if [ "$(dmidecode -s bios-vendor)" = 'Vultr' ];then
    HMUBUNTU=''
elif [ "$(dmidecode -s system-manufacturer)" = 'Microsoft Corporation' ];then
    HMUBUNTU='/root/'
elif [ -e /root/StackScript ]; then
    HMUBUNTU='/root/'
elif [ -e /home/ubuntu ]; then 
    HMUBUNTU='/home/ubuntu/'  
else
    HMUBUNTU=''
fi

verlt ${LOCAL_VERSION} ${LAST_VERSION::-1} && CPUPGRADE="Please upgrade CyberPanel version from ${LOCAL_VERSION} to ${LAST_VERSION},\nhttps://docs.litespeedtech.com/cloud/cyberpanel/#how-do-i-upgrade-cyberpanel" || CPUPGRADE="Your CyberPanel is up to date"
clear
cat <<EOF

********************************************************************************

$(echoCYAN 'Welcome to LiteSpeed One-Click CyberPanel Server.')
To keep this server secure, the firewalld is enabled.
CyberPanel One-Click Quickstart guide:
* $(echoB 'https://docs.litespeedtech.com/cloud/images/cyberpanel/')

In a web browser, you can view:
* CyberPanel: $(echoY "https://$MYIP:8090")
* phpMyAdmin: https://$MYIP:8090/dataBases/phpMyAdmin
* Rainloop:   https://$MYIP:8090/rainloop

On the server:
* You can get the CyberPanel admin password with the following command:
  $(echoY "sudo cat ${HMUBUNTU}.litespeed_password")
* You can get the Mysql cyberpanel user password with the following command:
  $(echoY "sudo cat ${HMUBUNTU}.db_password")

System Status:
  $(echo "Load :")$(echoG "$LOAD")
  $(echo "CPU  :") $(echoG "$CPU")
  $(echo "RAM  :") $(echoG "$RAM")
  $(echo "Disk :") $(echoG "$DISK")

$(echoG "${CPUPGRADE}")
********************************************************************************

EOF
