#!/bin/sh
#
# Configured as part of the 1-Click Image build process
echoY()
{
    FLAG=$1
    shift
    echo "\033[38;5;148m$FLAG\033[39m$@"
}
myip=$(curl -s ifconfig.me)
cat <<EOF
********************************************************************************
Welcome to One-Click OpenLiteSpeed WordPress Server.
To keep this server secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP) and 443 (HTTPS).
In a web browser, you can view:
* The WordPress+LiteSpeed One-Click Quickstart guide:
   https://docs.litespeedtech.com/cloud/wordpress
* The new WordPress site: $(echoY "http://$myip")
* The phpMyAdmin: http://$myip/phpmyadmin
On the server:
* The default web root is located at /var/www/html
* You can get the MySQL root password and MySQL WordPress user password with command:
   $(echoY "cat /home/ubuntu/.db_password")
* You can get the Web Admin admin password with the following command:
   $(echoY "cat /home/ubuntu/.litespeed_password")
* The WordPress Cache plugin, LSCache, is located at
   /var/www/html/wp-content/plugins/litespeed-cache
* The phpMyAdmin is located at /var/www/phpmyadmin
* A script will run that will allow you to add a domain to the web server and implement SSL.
********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
